---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: datadog
  namespace: datadog
spec:
  chart:
    repository: https://helm.datadoghq.com
    name: datadog/datadog
    version: 2.4.29
  values:
    targetSystem: "linux"
    datadog:
      logs:
        enabled: true
        containerCollectAll: true
        containerCollectUsingFiles: true
      collectEvents: true
      leaderElection: true
      apiKeyExistingSecret: "datadog-secret"
    clusterAgent:
      enabled: true
