apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: datadog-secret
  namespace: datadog
spec:
  encryptedData:
    api-key: AgC4ui7XZYhminSNDnH25ghtYFwjCL1lvzYXKJHXjsaHsVt33maAmT0hFN49cYaCd6qCIMVgySaXW6Fqa09mMCbArImzB0TMVKwu/qscYwJz/+45VNsa7/DZG3GNDDH6Q9wprvSfCc7doHq121yq7jtcKJ3KBmoqa9ZIGLAyVZCtR6lLP+PBkBUcZWNr69bhKMtVShY4boiZKZKHRBWHgKmwhJ2j4zF89GIaCcaxHAhZVZaz9blqUyOr0q5rUzi7m68itcFA6TWgDh+54mdEtiMe1zSzBtcWbagaLl8/MdLHJkD0+KZ37nirszZOQfgXUZIyM+GHbLOC2Xa1Ogp4DMz8YdlitkpuyYJW9t7iQdN8t31Sp0bCjNOIUAEqEYJZSpAoa234sI/712PJ9id+cJBP737CgdBab+z5/D2za7n8qARWRWO8zGHNGx+ep+dPfjzQctvTkZH/0YwgA9GQsjTQ2eg2T2TKeleWhKa8bZP4IRo085FFfvGk2uJNxwEYvieKWAkuce8o1YJFOsSs5SljhKy722Bkatrmvone2/UW1z328urJnBYpQGQRfHf+4IhqtgInYYwz6LUFkK6icxrep6XW9RvMtrUQM3foZRR5BREZvKFNVDAXfNrYgwQplmYgXPRXTiFpZFNZkH9Ri854Q8zSzdPd9bRr6R/XCHQc+8tm1NXKLgkXh+2oVrTiU756GDJ5a3Z7pixdC4lK6HfGoZaQbInp00WZKsVPAvMZlg==
  template:
    metadata:
      creationTimestamp: null
      name: datadog-secret
      namespace: datadog

