apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: datadog-secret
  namespace: datadog
spec:
  encryptedData:
    api-key: AgCil2SCskdiYmn7BAfhEwUTC4jrxQU0XrTwLdx6NN15Aq7ObKNrwT77kJLbGBg83MffxA+UmwPEz6T8lDMUKUyXsEpXuvLgCWpxjSf8L/ySp+wWmWpwCpy7tsrLFQsM0j/vEa/Ey2pjlAPu/eqqbp/wGZhOXBY8QkGITwnx0Kwlu9MIwvwidntB5Q6dM2DcYME0ArpEeQ2THCJEWS/TNIkNIizSnEA8vuRHgn11mnl9c+muQ9clplFulUdcibKtlSaVcoJE35GsKJYoGJkE1ce/S9sg1qA0QRaSCCrPsuKNVpNhPWXLR7bLfrA5cnFfxGsvMaTLaXfaAPKqoxHOmmS8GSEFODctUA0sJqUNqlpfmXExilYKZeaPQQ632wCC+KyFu/YJFHUT9H152O53+OE3oxyBVt9JUKIhvoqEZV0zEvsy9IkfF3RcjUQcS861B4M+rAysaR1xKBHTAxfj/y+F9kLTtjtrKyjAthtREjSelJaMVWCwmKBLV5RAM7YEDwYYnlx7w5rxMArq7z6tD3vIVYai0dAUx/CQi1dAbFAou10vsQfL7RsPGkaeqp144yKHGEzDn9V266rUn/11VIjkdP5I3nA3WKHoQP7OM0TWXHbDF3G8g+9rgc4QCHbZSRIZXjrIb0BVqmcuCYHJtSir3uLG0Wf9IOqy/EThwqjV2vV8cT+AOLK88DdwDyXalrr42qEzQcfsA8dPS54Zz/pqBB0QLdglz3zyzcRUsrGcxw==
  template:
    metadata:
      creationTimestamp: null
      name: datadog-secret
      namespace: datadog

